version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tasks
      JWT_SECRET: super-secret-key
    depends_on:
      - db